// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileDbDiagnostics = {
  schema_version: number;
  file_size_bytes: number | null;
  wal_mode: boolean;
};
