// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestoreValidateResponse = {
  valid: boolean;
  file_name: string;
  file_size: bigint;
  schema_version: string | null;
};
