// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed error payload emitted as a Tauri `"server-error"` event when the server
 * fails to start in the restart loop (after the initial setup phase).
 *
 * The `code` tag allows the frontend to branch on the specific failure kind.
 */
export type ServerStartupError =
  | {
      code: "migration_failed";
      path: string;
      message: string;
    }
  | {
      code: "schema_incompatible";
      path: string;
      unknown_migrations: Array<string>;
    }
  | { code: "not_mokumo_database"; path: string };
