// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppDiagnostics = {
  name: string;
  version: string;
  /**
   * Git commit SHA at build time; `None` when the binary was not built with vergen.
   */
  build_commit: string | null;
};
