// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeDiagnostics = {
  uptime_seconds: number;
  active_profile: "demo" | "production";
  setup_complete: boolean;
  is_first_launch: boolean;
  mdns_active: boolean;
  lan_url: string | null;
  host: string;
  port: number;
};
